# Generated by Django 2.2.6 on 2019-10-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_medicalhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalHistory',
            new_name='MedicalHistoryModel',
        ),
    ]
