# Generated by Django 2.2.6 on 2019-10-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20191016_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpMedicalInsuranceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=3)),
                ('aadhar_no', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('occupation', models.CharField(max_length=10)),
                ('profile_pic', models.FileField(upload_to='profile_pics/')),
                ('verify', models.BooleanField()),
            ],
        ),
    ]
