# Generated by Django 2.2.6 on 2019-10-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_prescriptionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='images',
            field=models.ImageField(upload_to='prescription/'),
        ),
    ]
