# Generated by Django 2.2.6 on 2019-10-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20191019_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='images',
            field=models.FileField(upload_to='prescription/'),
        ),
    ]
