# Generated by Django 2.2.6 on 2019-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20191019_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistorymodel',
            name='height',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalhistorymodel',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
